# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := CommandLineShell
ARDUINO_LIBS := EpoxyPromEsp AceCommon AceCRC AceRoutine AceUtils
include ../../../EpoxyDuino/EpoxyDuino.mk
