# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := CliTest
ARDUINO_LIBS := AUnit EpoxyPromEsp AceCRC AceCommon AceRoutine AceUtils
include ../../../EpoxyDuino/EpoxyDuino.mk
