# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := CrcEepromTest
ARDUINO_LIBS := EpoxyEepromEsp AUnit AceCommon AceCRC AceUtils AceRoutine
include ../../../EpoxyDuino/EpoxyDuino.mk
