# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ChannelCommandLineShell
ARDUINO_LIBS := EpoxyEepromEsp AceCommon AceCRC AceRoutine AceUtils
include ../../../EpoxyDuino/EpoxyDuino.mk
